server:
  port: 8080
spring:
  application:
    name: wisebear
  main:
    banner-mode: CONSOLE
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      group:
        liveness:
          include: diskSpace,ping
          show-details: always
  metrics:
    distribution:
      percentiles[http.server.requests]: 0.90,0.95,0.99
  info:
    git:
      mode: full